### ISSUE TITLE
issue 11760 is missed on issues.joomla.org

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#871] opened 2016-08-23 14:05 UTC
#### Steps to reproduce the issue

Issues.joomla.org

#### Expected result

See the entry there

#### Actual result

No entry for https://github.com/joomla/joomla-cms/pull/11760

**Comment by zero-24** [comment] 2016-08-23 14:09
Looks like we have a general bot issue?

https://issues.joomla.org/tracker/joomla-cms/11694

Misses the last comments from
https://github.com/joomla/joomla-cms/pull/11694#issuecomment-241742571

**Comment by mbabker** [comment] 2016-08-23 14:09
I'm getting really tired of ModSec...

**Comment by zero-24** [comment] 2016-08-23 14:10
:smile: How did it work before?

**Comment by mbabker** [comment] 2016-08-23 14:11
Odds are the old server didn't have ModSec on it.

**Comment by zero-24** [comment] 2016-08-23 14:13
Ok. Hmm but there should be a way to consume github hooks in a secure way do we have a way to contact github?

**Comment by mbabker** [comment] 2016-08-23 14:14
It's not GitHub, it's Rochen.

**Comment by zero-24** [comment] 2016-08-23 14:16
I mean ask github to get a secure configuration of mod security they have maybe some expirience in that? Or Rochen ask github howto configure it secure?

**Comment by zero-24** [comment] 2016-08-23 14:19
Can we do something like
https://developer.github.com/webhooks/securing/

**Comment by mbabker** [comment] 2016-08-23 14:21
Supposedly Rochen whitelisted GitHub stuff based on the data I gave them.  Apparently that's not happening.

The problem is our issues commonly have SQL scripts, JavaScript snippets, and HTML inlined into them.  Which triggers the rules long before our application runs.

And that page is only good for application level security measures.  It does nothing to address the web server stripping stuff.

**Comment by zero-24** [comment] 2016-08-23 14:23
Hmm thanks for checking

**Comment by zero-24** [comment] 2016-08-23 14:27
Hmm loks like that the cron synced it.. So we need to add our logic to the crons too? Like pending and labels?

**Comment by mbabker** [comment] 2016-08-23 14:30
So #692 needs to be synced, tested, and merged is what you're saying.

And the cron works fine because it initiates a request to GitHub's API and pulls the data as a response whereas the webhooks send the request to our server.  ModSecurity only filters incoming HTTP traffic, unless someone REALLY screwed up a configuration it shouldn't filter data from a curl request inside a PHP app.

**Comment by mbabker** [comment] 2016-08-23 14:32
BTW anyone with admin rights on whatever repo is having issues can check the webhook configurations on GitHub as it shows the log of all of the transactions and success/fail status.  You end up with something like the below meaning our server is once again misconfigured.

![screen shot 2016-08-23 at 9 31 29 am](https://cloud.githubusercontent.com/assets/368545/17895957/6edf129e-6914-11e6-9f18-f1e772631339.png)

**Comment by zero-24** [comment] 2016-08-23 14:35
i don't have admin rights on github repos. But also resending that would fail, correct?

**Comment by mbabker** [comment] 2016-08-23 14:36
Correct.

**Comment by mbabker** [comment] 2016-08-23 14:47
Per Rochen:

> Apache was rebuilt on the following the whitelisting I did previously; I've reapplied the changes now

**Closed by mbabker** 2016-08-23 14:47 UTC
