### ISSUE TITLE
New Feature Workflow label removed by bot

### ISSUE THREAD

**Issue by wojsmol** [joomla/jissues#1034] opened 2018-08-28 23:13 UTC
#### Steps to reproduce the issue
Please see https://github.com/joomla/joomla-cms/pull/21858

#### Expected result
New Feature Workflow label should persist after adding RTC

#### Actual result
New Feature Workflowis removed by @joomla-cms-bot when RTC is added 

#### System information (as much as possible)

**Comment by mbabker** [comment] 2018-08-28 23:15
Duplicate of #947

**Closed by mbabker** 2018-08-28 23:15 UTC
