### ISSUE TITLE
Emoticons break descriptions

### ISSUE THREAD

**Issue by dgt41** [joomla/jissues#556] opened 2014-11-09 00:24 UTC
#### Steps to reproduce the issue
Add a new PR with a title and in the description add an emoticon

#### Expected result
Description with emoticon code or an icon

#### Actual result

The description breaks at the first emoticon and no further text gets in the database 

#### System information (as much as possible)
PR:      https://github.com/joomla/joomla-cms/pull/5058
Tracker: http://issues.joomla.org/tracker/joomla-cms/5058

**Comment by b2z** [comment] 2015-01-11 20:22
@dgt41 I've just tested and everything is good. See the prove:
http://issues.joomla.org/tracker/jtests/50

**Comment by dgt41** [comment] 2015-01-11 21:02
Seems to be ok now. I will close this one<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/556">issues.joomla.org/jtracker/556</a>.</sub>

**Comment by dgt41** [comment] 2015-01-19 01:08
Ok I came across to this problem once again!
I realize that the problem isn’t the bot but maybe the editor of jissues?
Anyway these are two links and two images that show the problem
on github https://github.com/joomla/joomla-cms/pull/5815
![screen shot 2015-01-18 at 18 26 00](http://issues.joomla.org/uploads/2/8c06a2f88b942f5720e39661af99ffb9.png)

And on jissues http://issues.joomla.org/tracker/joomla-cms/5815

![screen shot 2015-01-18 at 18 27 17](http://issues.joomla.org/uploads/1/61d465e39e9f55f81b07e39f0c842c0b.png)

As you can see on Jissues nothing gets parsed after the emoticon!

**Comment by zero-24** [comment] 2015-01-19 07:12
Confirmed. The strange ist the following image. If we follow the diff on the Tracker the bot added the lines after the emoticon but it is not there:

![diff](https://cloud.githubusercontent.com/assets/2596554/5797038/d565c49a-9fb2-11e4-8ca8-b1288bbd3420.PNG)

**Comment by b2z** [comment] 2015-01-19 08:06
I can't fully understand at what moment it happens.

@dgt41 can you describe step by step what you did and I will try to reproduce. Thank you.

**Comment by mbabker** [comment] 2015-01-19 13:50
My two hunches right now are that our controller isn't handling filtering it very well (which may mean an issue in Joomla/Filter) or the GitHub API isn't handling it very well.  To debug, I'd suggest dumping the data just before we send a request to the API to render the markdown data and see what the description field contains.  If it's good before that point, then that seems to point to either a GitHub API issue or an issue with Joomla/GitHub and Joomla/HTTP and handling the request for that; whereas if it is missing content before that point then it would seem to point to a filtering issue.

**Comment by dgt41** [comment] 2015-01-19 14:03
@zero-24 The strange character should be unicode `U+1F603` the third one in this [list](http://apps.timwhitlock.info/emoji/tables/unicode)
Any idea where is the mapping for emoticons?

**Comment by dgt41** [comment] 2015-01-19 14:12
@b2z Steps to reproduce:
Create a new PR on github, some title etc but in description add an emoticon with its Unicode (not as :smilr:)
Then let the bot fetch it
and then try to access it in Jissues

**Comment by b2z** [comment] 2015-01-20 11:55
>but in description add an emoticon with its Unicode

May be this is the problem. I will try to reproduce.

**Comment by b2z** [comment] 2015-02-01 17:47
@dgt41 I am trying to reproduce, but do not understand how to add the emotion in Unicode. I tried to use U+1F603 but it is only text. Please explain how to use it :)

**Comment by dgt41** [comment] 2015-02-01 18:03
@b2z  can you copy paste 😉 ?

**Comment by b2z** [comment] 2015-02-01 18:18
Ah ok got it now. `😉`

**Comment by b2z** [comment] 2015-02-01 19:30
So I have tested and I do not know how to fix it :( I traced the data till the `updateObject()` method and here is how the fields looks like just before the query statement execution:

![emoji_data](https://cloud.githubusercontent.com/assets/3051676/5993439/41011280-aa59-11e4-949c-b34a87c489e3.png)

As you can see `description` and `description_raw` are good. But after saving in the DB they looks like this:

![emoji_data_db](https://cloud.githubusercontent.com/assets/3051676/5993440/44dcef5a-aa59-11e4-8a63-cbd301d52acc.png)

:(

**Comment by mbabker** [comment] 2015-02-01 19:37
Can the database not handle the characters that are getting printed after the closing tag?  The table is defined with a utf8 charset, the columns in question are utf8_general_ci collation and utf8 encoded.

**Comment by b2z** [comment] 2015-02-01 19:46
Seems so. I trying to Google for it, but nothing found at the moment.

**Comment by dgt41** [comment] 2015-02-02 00:33
Isn't this a filtering problem? My guess is tha `<g-emoji` is not a valid, known tag in the filters and thus rejected.

**Comment by mbabker** [comment] 2015-02-02 00:39
It wouldn't make it to the database if there were a filtering problem.

**Comment by dgt41** [comment] 2015-02-02 01:27
@mbabker you re right, of course...
Found this:
`create table MyEmoji (emojicolumn VARCHAR(255) CHARACTER SET utf8mb4) default character set utf8mb4;`
> Emoji is represented as 4 byte characters. That’s mean your MySQL table charset should be set as utf8mb4.

**Comment by b2z** [comment] 2015-02-02 09:17
If we are running MySQL 5.5.3+ then we could [switch](https://mathiasbynens.be/notes/mysql-utf8mb4) to `utf8mb4`.

**Comment by mbabker** [comment] 2015-02-02 13:54
We're on 5.6 on the server.

**Comment by b2z** [comment] 2015-03-01 06:54
@mbabker does it make sense to switch to `utf8mb4` ?

**Comment by mbabker** [comment] 2015-03-01 14:56
I don't see an issue with it.

**Comment by b2z** [comment] 2015-03-02 14:14
Then close it :tongue:

**Comment by mbabker** [comment] 2015-03-02 14:45
How about a PR to update the default schema to use the `utf8mb4` character set :stuck_out_tongue:

**Comment by b2z** [comment] 2015-03-02 14:54
@mbabker you are so kind :grimacing:

**Closed** 2015-04-11 10:33 UTC
Labels: bug

**Comment by mbabker** [comment] 2015-04-11 10:47
So with any luck, 😉will work now...
