### ISSUE TITLE
Blank Categories and Labels fields in Joomla Issue Tracker

### ISSUE THREAD

**Issue by ceford** [joomla/jissues#1072] opened 2020-02-01 11:03 UTC
#### Steps to reproduce the issue

Just open the the Joomla CMS Tracker and click Search Tools. 
Click either the Categories or Labels dropdown lists.

#### Expected result

List panels should appear populated with items to select.

#### Actual result

The list panels are blank!

#### System information (as much as possible)

Not my system!

#### Additional comments

The problem is caused by these styles in template_3.0.0.min.css:
.btn-group {
	font-size: 0;
} 

.btn-toolbar {
	font-size: 0;
} 
I can see the lists using the css Inspector to unset them.

**Comment by mbabker** [comment] 2020-02-01 20:14
Those rules aren’t what should be changed.  They’re the defaults from Bootstrap 2.3 (why, I don’t know, but that’s beside the point).  The issue is probably something to do with how the various UI plugins are being loaded and used (basically either incorrect markup, incorrect CSS order, or a missing override).  Changing those rules in the base template affecting every .org site isn’t the right fix here.

**Comment by ceford** [comment] 2020-02-02 06:21
On second look it seems to be a more substantial coding error: the grey search filters have both a drop-down list and a button list. The others have just a drop-down list.

**Comment by richard67** [comment] 2020-02-17 21:48
Could that be related to #1070 ? Some assets not loaded right?

**Comment by mbabker** [comment] 2020-02-18 15:35
Fixed via https://github.com/joomla/jissues/commit/c10016e84946c4872c98abad015d49f8f3478ad6

Undocumented in the 1.13 release notes of the `bootstrap-select` package is the fact that it no longer supports Bootstrap 2.  Downgrading and locking to 1.12 fixes this.

**Closed by mbabker** 2020-02-18 15:35 UTC
