### ISSUE TITLE
Add systeminfo to issue

### ISSUE THREAD

**Issue by slibbe** [joomla/jissues#760] opened 2016-03-17 10:03 UTC
When creating (or adding to) an issue it would be nice to include the Joomla systeminfo file.

#### Steps to reproduce the issue
In issue 'Add files' > browse to systeminfo_etc.json > file type not allowed.
> browse to systeminfo_etc.txt > incorrect MIME-type.

#### Expected result
Correctly attaching systeminfo-file.

#### Actual result
In case of .json : file type not allowed
In case of .txt : incorrect MIME-type.

**Comment by mbabker** [comment] 2016-03-17 14:11
The application only supports uploads for what [GitHub will support](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).  GitHub doesn't support JSON files right now so that error's to be expected.  Still looking on the TXT file issue.

**Comment by b2z** [comment] 2016-03-17 14:13
@mbabker may be TXT is not added to config file?

**Comment by mbabker** [comment] 2016-03-17 14:19
It is.

**Comment by b2z** [comment] 2016-03-17 14:21
That's interesting - I have no problem adding it [on my testing server](http://jtracker.j4devs.ru/tracker/jissues-test/3).

**Comment by mbabker** [comment] 2016-03-17 14:22
Nor me locally.

**Comment by mbabker** [comment] 2016-03-17 14:23
Found the issue.  At least in my case, the server is uploading it with a `text/x-c++` MIME.

**Comment by mbabker** [comment] 2016-03-17 14:34
Well I've added some logging to the uploader so now in the app.log we'll get some data on why uploads fail.

**Comment by mbabker** [comment] 2016-03-18 15:31
I've attached here the file I'm testing with (which is coming out of Joomla via the system info export feature).  It uploads fine in GitHub and on my localhost.  @b2z I couldn't upload it on your system, got the MIME error.  So my guess is some kind of PHP or Apache setting is giving us issues, I just don't know what.  I also filed a ticket with hosting to see if they have any ideas.

Interestingly enough, Joomla's LICENSE.txt file wouldn't upload either; that tried to upload with a `text/x-pascal` MIME.

[systeminfo-2016-03-17T10-08-09-04-00.txt](https://github.com/joomla/jissues/files/179905/systeminfo-2016-03-17T10-08-09-04-00.txt)

**Comment by mbabker** [comment] 2016-03-18 16:33
So, random question.  Do we actually NEED the MIME type validation?  https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/ seems to imply the answer is no.

**Comment by mbabker** [comment] 2016-03-18 20:38
@b2z What's your server's `fileinfo` PHP configuration?  Specifically I'm interested in whether you've got `libmagic` enabled and what version if so.

**Comment by b2z** [comment] 2016-03-19 07:32
@mbabker nothing special there:
```
fileinfo support = enabled
version = 1.0.5
```

I'm running PHP 5.4.45. Weird issue :(

**Comment by mbabker** [comment] 2016-03-19 15:28
It's the libmagic library that makes a difference.  With it, uploads with different MIME types on .txt files is fine.  Without it, basically whatever MIME the file has is what gets used in the end.  So it's definitely environmental.

Now the issue is how do we deal with not having that library consistently available?  The MIME validations we have are going to be too strict with what the CMS is exporting right now.

**Comment by b2z** [comment] 2016-03-20 04:38
Lets drop the validation completely or for `.txt` only?

**Comment by mbabker** [comment] 2016-03-20 22:45
For .txt I'd say skip it for the short term.  The Joomla servers running PHP 5.6 have libmagic installed so they wouldn't hit this issue (and it looks like it might be a general PHP change between 5.5 and 5.6; all my 5.5 environments don't have that library yet 5.6 does).  So once the server gets upgraded we're good.

**Comment by mbabker** [comment] 2016-03-25 19:58
Workaround merged.

**Closed by mbabker** 2016-03-25 19:58 UTC
Labels: server issue
